# Generated by Django 5.2.5 on 2026-01-26 19:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('milestone', 'Jalon'), ('skill', 'Compétence'), ('dedication', 'Dévouement'), ('excellence', 'Excellence')], max_length=20)),
                ('badge_image', models.ImageField(upload_to='achievements/')),
                ('condition_rule', models.JSONField(default=dict)),
                ('points_reward', models.IntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Succès',
                'verbose_name_plural': 'Succès',
            },
        ),
        migrations.CreateModel(
            name='LearningPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_level', models.CharField(blank=True, max_length=20)),
                ('courses_completed', models.IntegerField(default=0)),
                ('lessons_completed', models.IntegerField(default=0)),
                ('exercises_completed', models.IntegerField(default=0)),
                ('total_study_time_seconds', models.BigIntegerField(default=0)),
                ('average_score', models.FloatField(default=0)),
                ('last_learning_date', models.DateField(blank=True, null=True)),
                ('learning_streak_days', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='learning_path', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Chemin d'Apprentissage",
                'verbose_name_plural': "Chemins d'Apprentissage",
            },
        ),
        migrations.CreateModel(
            name='PerformanceAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_date', models.DateField(auto_now_add=True)),
                ('overall_score', models.FloatField(default=0)),
                ('subjects_scores', models.JSONField(default=dict)),
                ('strengths', models.JSONField(default=list)),
                ('weaknesses', models.JSONField(default=list)),
                ('recommendations', models.JSONField(default=list)),
                ('suggested_focus_areas', models.JSONField(default=list)),
                ('improvement_trends', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Analyse de Performance',
                'verbose_name_plural': 'Analyses de Performance',
                'ordering': ['-analysis_date'],
            },
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Non commencé'), ('in_progress', 'En cours'), ('completed', 'Complété'), ('mastered', 'Maîtrisé')], default='not_started', max_length=20)),
                ('progress_percentage', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('exercises_completed', models.IntegerField(default=0)),
                ('exercises_correct', models.IntegerField(default=0)),
                ('average_exercise_score', models.FloatField(default=0)),
                ('time_spent_seconds', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='courses.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Progression de Leçon',
                'verbose_name_plural': 'Progressions de Leçon',
                'unique_together': {('student', 'lesson')},
            },
        ),
        migrations.CreateModel(
            name='StudentAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progress.achievement')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Succès Étudiant',
                'verbose_name_plural': 'Succès Étudiants',
                'unique_together': {('student', 'achievement')},
            },
        ),
    ]
