#!/bin/bash

# ============================================
# 🤖 QUICK TRAINING - Entraînement rapide
# Commandes essentielles pour l'entraînement ML
# ============================================

echo "╔════════════════════════════════════════════════════════════╗"
echo "║  🤖 INTELLIGENT TUTOR - QUICK TRAINING GUIDE              ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo -e "${BLUE}=== 🚀 LE PLUS RAPIDE (UNE LIGNE!) ===${NC}"
echo ""
echo "👇 COPIEZ-COLLEZ CETTE COMMANDE:"
echo ""
echo -e "${GREEN}python manage.py train_ml_models --all --activate${NC}"
echo ""
echo "⏱️  Durée: 5-10 minutes"
echo "📊 Résultat: 4 modèles entraînés et activés"
echo ""
echo "════════════════════════════════════════════════════════════"
echo ""

echo -e "${BLUE}=== ✅ VÉRIFICATIONS AVANT ===${NC}"
echo ""
echo "1️⃣  Python version:"
echo "    python --version"
echo ""
echo "2️⃣  Django check:"
echo "    python manage.py check"
echo ""
echo "3️⃣  Données disponibles:"
echo "    python manage.py shell"
echo "    >>> from apps.courses.models import Course"
echo "    >>> Course.objects.count()"
echo ""
echo "════════════════════════════════════════════════════════════"
echo ""

echo -e "${BLUE}=== 🎯 ENTRAÎNEMENT COMPLET ===${NC}"
echo ""
echo "Option 1: Entraîner TOUS les modèles"
echo "  ${GREEN}python manage.py train_ml_models --all --activate${NC}"
echo ""
echo "Option 2: Entraîner UN modèle"
echo "  ${GREEN}python manage.py train_ml_models --model correction --activate${NC}"
echo "  ${GREEN}python manage.py train_ml_models --model error_analysis --activate${NC}"
echo "  ${GREEN}python manage.py train_ml_models --model recommendation --activate${NC}"
echo "  ${GREEN}python manage.py train_ml_models --model performance --activate${NC}"
echo ""
echo "Option 3: Entraîner SANS activer (pour tester)"
echo "  ${GREEN}python manage.py train_ml_models --all${NC}"
echo ""
echo "════════════════════════════════════════════════════════════"
echo ""

echo -e "${BLUE}=== 📊 VÉRIFIER LES RÉSULTATS ===${NC}"
echo ""
echo "Dans Django shell:"
echo "  ${GREEN}python manage.py shell${NC}"
echo ""
echo "Puis exécutez:"
echo ""
echo "  from apps.recommendations.models import MLModelVersion"
echo ""
echo "  # Voir tous les modèles"
echo "  for m in MLModelVersion.objects.all():"
echo "      print(f'{m.model_name}: {m.status} (Accuracy: {m.accuracy})')"
echo ""
echo "  # Ou une version plus simple"
echo "  MLModelVersion.objects.values('model_name', 'status', 'accuracy')"
echo ""
echo "════════════════════════════════════════════════════════════"
echo ""

echo -e "${BLUE}=== 🧪 TESTER LES MODÈLES (APRÈS ENTRAÎNEMENT) ===${NC}"
echo ""
echo "Test 1: Correction d'exercice"
echo "  ${GREEN}curl -X POST http://localhost:8000/api/correction/ \\${NC}"
echo "  ${GREEN}  -H 'Content-Type: application/json' \\${NC}"
echo "  ${GREEN}  -d '{\"student_answer\": \"2+2=5\", \"correct_answer\": \"2+2=4\", \"subject\": \"math\"}'${NC}"
echo ""
echo "Test 2: Analyse d'erreur"
echo "  ${GREEN}curl -X POST http://localhost:8000/api/exercise-analysis/ \\${NC}"
echo "  ${GREEN}  -H 'Content-Type: application/json' \\${NC}"
echo "  ${GREEN}  -d '{\"student_answer\": \"Il va\", \"correct_answer\": \"Il ira\", \"subject\": \"french\"}'${NC}"
echo ""
echo "Test 3: Status des modèles"
echo "  ${GREEN}curl http://localhost:8000/api/models/status/${NC}"
echo ""
echo "════════════════════════════════════════════════════════════"
echo ""

echo -e "${BLUE}=== 🔄 RÉENTRAÎNER (PLUS TARD) ===${NC}"
echo ""
echo "Réentraîner après ajout de données:"
echo "  ${GREEN}python manage.py train_ml_models --all --activate${NC}"
echo ""
echo "Réentraîner automatiquement chaque jour à 2h:"
echo "  ${GREEN}crontab -e${NC}"
echo "  # Ajouter cette ligne:"
echo "  # 0 2 * * * cd /home/tanou/Bur/projetWeb/intelligent_tutor && python manage.py train_ml_models --all --activate"
echo ""
echo "════════════════════════════════════════════════════════════"
echo ""

echo -e "${BLUE}=== 📝 LOGS ===${NC}"
echo ""
echo "Voir les logs d'entraînement:"
echo "  ${GREEN}tail -f logs/training.log${NC}"
echo ""
echo "Voir les 50 dernières lignes:"
echo "  ${GREEN}tail -50 logs/training.log${NC}"
echo ""
echo "════════════════════════════════════════════════════════════"
echo ""

echo -e "${BLUE}=== ⚠️  EN CAS DE PROBLÈME ===${NC}"
echo ""
echo "❌ 'No courses found' ou 'Module not found'"
echo "   → Installer les dépendances:"
echo "   ${GREEN}pip install -r requirements.txt${NC}"
echo ""
echo "❌ 'Database error'"
echo "   → Vérifier les migrations:"
echo "   ${GREEN}python manage.py migrate${NC}"
echo ""
echo "❌ 'No data to train on'"
echo "   → Importer les cours:"
echo "   ${GREEN}bash import_faso_courses.sh${NC}"
echo ""
echo "❌ 'Modèles ne s'activent pas'"
echo "   → Relancer sans --activate d'abord:"
echo "   ${GREEN}python manage.py train_ml_models --all${NC}"
echo "   Puis activer manuellement dans Django shell"
echo ""
echo "════════════════════════════════════════════════════════════"
echo ""

echo -e "${GREEN}╔════════════════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║  📚 DOCUMENTATION COMPLÈTE:                              ║${NC}"
echo -e "${GREEN}║                                                            ║${NC}"
echo -e "${GREEN}║  • ML_TRAINING_TUTORIAL.md - Guide complet               ║${NC}"
echo -e "${GREEN}║  • ML_TRAINING_GUIDE.md - Guide détaillé                 ║${NC}"
echo -e "${GREEN}║  • ML_EXAMPLES.py - Exemples de code                     ║${NC}"
echo -e "${GREEN}╚════════════════════════════════════════════════════════════╝${NC}"
echo ""

echo "👉 PRÊT? Lancez l'entraînement:"
echo ""
echo -e "${GREEN}    python manage.py train_ml_models --all --activate${NC}"
echo ""
