# Generated by Django 6.0 on 2026-01-31 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('primary_cp1', 'CP1 (Primaire)'), ('primary_cp2', 'CP2 (Primaire)'), ('primary_ce1', 'CE1 (Primaire)'), ('primary_ce2', 'CE2 (Primaire)'), ('primary_cm1', 'CM1 (Primaire)'), ('primary_cm2', 'CM2 (Primaire)'), ('secondary_6eme', '6ème (Collège)'), ('secondary_5eme', '5ème (Collège)'), ('secondary_4eme', '4ème (Collège)'), ('secondary_3eme', '3ème (Collège)'), ('lycee_2nde', 'Lycée (Seconde)'), ('lycee_1ere', 'Lycée (Première)'), ('lycee_tles', 'Lycée (Terminale)')], max_length=20),
        ),
    ]
