# Generated by Django 5.2.5 on 2026-01-26 19:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercises', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdaptiveRecommendationEngine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performance_weight', models.FloatField(default=0.3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('interest_weight', models.FloatField(default=0.3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('learning_style_weight', models.FloatField(default=0.2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('engagement_weight', models.FloatField(default=0.2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('recommendation_frequency_hours', models.IntegerField(default=24)),
                ('max_recommendations_per_session', models.IntegerField(default=5)),
                ('algorithm_version', models.CharField(default='v1.0', max_length=50)),
                ('last_recommendation_generated', models.DateTimeField(blank=True, null=True)),
                ('total_recommendations_generated', models.IntegerField(default=0)),
                ('average_recommendation_quality', models.FloatField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_engine', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Moteur de Recommandation Adaptatif',
                'verbose_name_plural': 'Moteurs de Recommandation Adaptatifs',
            },
        ),
        migrations.CreateModel(
            name='ContentRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('course', 'Cours'), ('lesson', 'Leçon'), ('exercise', 'Exercice'), ('resource', 'Ressource')], max_length=20)),
                ('content_id', models.IntegerField()),
                ('content_title', models.CharField(max_length=255)),
                ('confidence_score', models.FloatField(help_text='Confidence of recommendation (0-1)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('reason', models.TextField()),
                ('recommendation_factors', models.JSONField(default=dict)),
                ('is_viewed', models.BooleanField(default=False)),
                ('is_accepted', models.BooleanField(default=False)),
                ('user_rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recommandation de Contenu',
                'verbose_name_plural': 'Recommandations de Contenu',
                'ordering': ['-confidence_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ErrorAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_type', models.CharField(choices=[('conceptual', 'Erreur conceptuelle'), ('calculation', 'Erreur de calcul'), ('reading', 'Erreur de lecture'), ('careless', "Erreur d'inattention"), ('logical', 'Erreur logique'), ('other', 'Autre')], max_length=20)),
                ('concept_involved', models.CharField(help_text="Concept/notion impliqué(e) dans l'erreur", max_length=255)),
                ('description', models.TextField(help_text="Description de l'erreur")),
                ('student_answer', models.TextField()),
                ('correct_answer', models.TextField()),
                ('concept_understanding_level', models.CharField(choices=[('not_understood', 'Non compris'), ('partial', 'Partiellement compris'), ('mostly_understood', 'Bien compris'), ('fully_understood', 'Parfaitement compris')], default='not_understood', max_length=20)),
                ('misconception_identified', models.TextField(blank=True, help_text='Conception erronée identifiée')),
                ('root_cause', models.TextField(blank=True, help_text="Cause racine de l'erreur")),
                ('partial_credit', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('suggested_topics', models.JSONField(default=list, help_text='Topics à réviser')),
                ('similar_past_errors', models.IntegerField(default=0, help_text="Nombre d'erreurs similaires passées")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.exercise')),
                ('exercise_attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='error_analysis', to='exercises.exerciseattempt')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='error_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Analyse d'Erreur",
                'verbose_name_plural': "Analyses d'Erreurs",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IntelligentRevisionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept', models.CharField(help_text='Concept à réviser', max_length=255)),
                ('reason', models.TextField(help_text='Raison de la révision recommandée')),
                ('priority_score', models.FloatField(default=0.5, help_text='Priorité (0-1)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('error_count', models.IntegerField(default=0, help_text="Nombre d'erreurs liées à ce concept")),
                ('last_error', models.DateTimeField(blank=True, null=True)),
                ('related_exercises', models.JSONField(default=list, help_text="ID d'exercices connexes")),
                ('related_lessons', models.JSONField(default=list, help_text='ID de leçons connexes')),
                ('custom_tips', models.JSONField(default=list, help_text='Conseils personnalisés')),
                ('status', models.CharField(choices=[('recommended', 'Recommandé'), ('in_progress', 'En cours'), ('completed', 'Complété'), ('mastered', 'Maîtrisé')], default='recommended', max_length=20)),
                ('revision_attempts', models.IntegerField(default=0)),
                ('mastery_score', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revision_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Élément de Révision Intelligente',
                'verbose_name_plural': 'Éléments de Révision Intelligents',
                'ordering': ['-priority_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LearningStyleProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_style', models.CharField(choices=[('visual', 'Visuel'), ('auditory', 'Auditif'), ('kinesthetic', 'Kinesthésique'), ('reading_writing', 'Lecture/Écriture'), ('mixed', 'Mixte')], default='visual', max_length=20)),
                ('secondary_style', models.CharField(blank=True, choices=[('visual', 'Visuel'), ('auditory', 'Auditif'), ('kinesthetic', 'Kinesthésique'), ('reading_writing', 'Lecture/Écriture'), ('mixed', 'Mixte')], max_length=20)),
                ('visual_preference', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('auditory_preference', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('kinesthetic_preference', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('reading_writing_preference', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('pace_preference', models.FloatField(default=1.0, help_text='Learning pace multiplier (0.5 = slow, 1.0 = normal, 2.0 = fast)', validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(2.0)])),
                ('difficulty_preference', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='learning_style_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Profil de Style d'Apprentissage",
                'verbose_name_plural': "Profils de Styles d'Apprentissage",
            },
        ),
        migrations.CreateModel(
            name='MLModelVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(choices=[('recommendation', 'Recommandation'), ('performance', 'Performance'), ('learning_style', "Style d'apprentissage"), ('difficulty', 'Difficulté')], max_length=50)),
                ('version', models.CharField(default='1.0.0', max_length=20)),
                ('status', models.CharField(choices=[('training', "En cours d'entraînement"), ('active', 'Actif'), ('archived', 'Archivé'), ('failed', 'Échoué')], default='training', max_length=20)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('precision', models.FloatField(blank=True, null=True)),
                ('recall', models.FloatField(blank=True, null=True)),
                ('f1_score', models.FloatField(blank=True, null=True)),
                ('rmse', models.FloatField(blank=True, null=True)),
                ('mae', models.FloatField(blank=True, null=True)),
                ('r2', models.FloatField(blank=True, null=True)),
                ('training_samples', models.IntegerField(default=0)),
                ('training_duration_seconds', models.IntegerField(default=0)),
                ('feature_count', models.IntegerField(default=0)),
                ('hyperparameters', models.JSONField(default=dict)),
                ('model_path', models.CharField(blank=True, max_length=255)),
                ('scaler_path', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trained_at', models.DateTimeField(blank=True, null=True)),
                ('deployed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-trained_at'],
                'indexes': [models.Index(fields=['model_type', '-trained_at'], name='recommendat_model_t_de7c0e_idx'), models.Index(fields=['status'], name='recommendat_status_a0c04e_idx')],
            },
        ),
        migrations.CreateModel(
            name='ModelEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_set_size', models.IntegerField(default=0)),
                ('test_set_percentage', models.FloatField(default=0.2)),
                ('confusion_matrix', models.JSONField(blank=True, null=True)),
                ('class_report', models.JSONField(blank=True, null=True)),
                ('residuals_mean', models.FloatField(blank=True, null=True)),
                ('residuals_std', models.FloatField(blank=True, null=True)),
                ('cv_scores', models.JSONField(default=list)),
                ('cv_mean', models.FloatField(blank=True, null=True)),
                ('cv_std', models.FloatField(blank=True, null=True)),
                ('feature_importance', models.JSONField(default=dict)),
                ('shap_values', models.JSONField(blank=True, null=True)),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
                ('model', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='recommendations.mlmodelversion')),
            ],
        ),
        migrations.CreateModel(
            name='ModelPredictionCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_hash', models.CharField(db_index=True, max_length=64)),
                ('prediction', models.JSONField()),
                ('confidence', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='recommendations.mlmodelversion')),
            ],
        ),
        migrations.CreateModel(
            name='RecommendationFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('useful', 'Utile'), ('not_useful', 'Pas utile'), ('irrelevant', 'Hors de propos'), ('too_easy', 'Trop facile'), ('too_hard', 'Trop difficile')], max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='recommendations.contentrecommendation')),
            ],
            options={
                'verbose_name': 'Retour sur Recommandation',
                'verbose_name_plural': 'Retours sur Recommandation',
            },
        ),
        migrations.CreateModel(
            name='SmartExplanation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explanation_type', models.CharField(choices=[('error_specific', 'Basée sur erreur'), ('concept_based', 'Basée sur concept'), ('reminder', 'Rappel'), ('reinforcement', 'Renforcement'), ('alternative', 'Approche alternative')], max_length=20)),
                ('content', models.TextField(help_text="Contenu de l'explication")),
                ('is_interactive', models.BooleanField(default=False, help_text='Contient des éléments interactifs')),
                ('uses_examples', models.BooleanField(default=True, help_text='Inclut des exemples concrets')),
                ('uses_analogies', models.BooleanField(default=False, help_text='Utilise des analogies')),
                ('student_rating', models.IntegerField(blank=True, help_text="Évaluation par l'étudiant (1-5)", null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('was_helpful', models.BooleanField(blank=True, null=True)),
                ('follow_up_score', models.FloatField(blank=True, help_text='Score au suivi (0-100)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('exercise_attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smart_explanations', to='exercises.exerciseattempt')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smart_explanations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Explication Intelligente',
                'verbose_name_plural': 'Explications Intelligentes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epoch', models.IntegerField(default=0)),
                ('loss', models.FloatField(blank=True, null=True)),
                ('val_loss', models.FloatField(blank=True, null=True)),
                ('metrics', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_logs', to='recommendations.mlmodelversion')),
            ],
            options={
                'ordering': ['model', 'epoch'],
            },
        ),
        migrations.AddIndex(
            model_name='contentrecommendation',
            index=models.Index(fields=['student', '-created_at'], name='recommendat_student_5afb16_idx'),
        ),
        migrations.AddIndex(
            model_name='contentrecommendation',
            index=models.Index(fields=['student', 'is_viewed'], name='recommendat_student_ce48bb_idx'),
        ),
        migrations.AddIndex(
            model_name='erroranalysis',
            index=models.Index(fields=['student', '-created_at'], name='recommendat_student_0abed2_idx'),
        ),
        migrations.AddIndex(
            model_name='erroranalysis',
            index=models.Index(fields=['error_type'], name='recommendat_error_t_72202c_idx'),
        ),
        migrations.AddIndex(
            model_name='intelligentrevisionitem',
            index=models.Index(fields=['student', 'status'], name='recommendat_student_c999c2_idx'),
        ),
        migrations.AddIndex(
            model_name='intelligentrevisionitem',
            index=models.Index(fields=['-priority_score'], name='recommendat_priorit_e95e63_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='intelligentrevisionitem',
            unique_together={('student', 'concept')},
        ),
        migrations.AddIndex(
            model_name='modelpredictioncache',
            index=models.Index(fields=['input_hash', 'expires_at'], name='recommendat_input_h_393a1c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='modelpredictioncache',
            unique_together={('model', 'input_hash')},
        ),
        migrations.AddIndex(
            model_name='smartexplanation',
            index=models.Index(fields=['student', '-created_at'], name='recommendat_student_d77b2f_idx'),
        ),
        migrations.AddIndex(
            model_name='smartexplanation',
            index=models.Index(fields=['explanation_type'], name='recommendat_explana_9df2ed_idx'),
        ),
    ]
